theme: 
  - osuny
  - osuny-plugin-centered-header
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: /assets/images/logo-papote.svg
    footer: /assets/images/logo-papote.svg
  home:
    head:
      title: site